### PR TITLE
Result scoring

### PR DESCRIPTION
**Pull request by blabno**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/elastic-harvesterjs/pull/76%23issuecomment-163660881%22%2C%20%22https%3A//github.com/agco/elastic-harvesterjs/pull/76%23issuecomment-163871213%22%2C%20%22https%3A//github.com/agco/elastic-harvesterjs/pull/76%23issuecomment-167066027%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/elastic-harvesterjs/pull/76%23issuecomment-163660881%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40ssebro%20this%20is%20the%20best%20I%20could%20get%20so%20far%2C%20but%20it%20looks%20like%20it%20breaks%20some%20other%20tests.%20Probably%20we%20could%20add%20additional%20param%20to%20turn%20scoring%20on/off%3F%22%2C%20%22created_at%22%3A%20%222015-12-10T15%3A35%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/431064%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/blabno%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ok%2C%20I%27ve%20got%20all%20tests%20passing%21%22%2C%20%22created_at%22%3A%20%222015-12-11T08%3A11%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/431064%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/blabno%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40ssebro%20I%27ve%20added%20comments%20to%20the%20code.%22%2C%20%22created_at%22%3A%20%222015-12-24T08%3A13%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/431064%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/blabno%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/agco/elastic-harvesterjs/pull/76#issuecomment-163660881'>General Comment</a></b>
- <a href='https://github.com/blabno'></a> @ssebro this is the best I could get so far, but it looks like it breaks some other tests. Probably we could add additional param to turn scoring on/off?
- <a href='https://github.com/blabno'></a> Ok, I've got all tests passing!
- <a href='https://github.com/blabno'></a> @ssebro I've added comments to the code.

<a href='https://www.codereviewhub.com/agco/elastic-harvesterjs/pull/76?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/agco/elastic-harvesterjs/pull/76?approve=1'></a>&nbsp;<a href='https://github.com/agco/elastic-harvesterjs/pull/76'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by ssebro** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/agco/elastic-harvesterjs/pull/76'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by blabno** [comment]
@ssebro this is the best I could get so far, but it looks like it breaks some other tests. Probably we could add additional param to turn scoring on/off?

**Comment by blabno** [comment]
Ok, I've got all tests passing!

**Comment by blabno** [comment]
@ssebro I've added comments to the code.

**Pull request merged**
